apiVersion: v1
kind: Pod
metadata:
  name: edge-app
  namespace: edge 
spec:
  terminationGracePeriodSeconds: 30
  containers:  
    - name: edge-app
      image: arskale/edgerepo01:arm64v8-9
      imagePullPolicy: "Always"
      securityContext:
        privileged: true
        allowPrivilegeEscalation: true
  nodeName: default-edge-node
